Connect-MgGraph -TenantId $TenantId -ClientSecretCredential $ClientSecretCredential | Out-Null
Connect-MicrosoftTeams -Credential $credential -InformationAction SilentlyContinue | Out-Null
    
Grant-CsTenantDialPlan -Identity adriana.rios.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity anacarolinaelias.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity anacelia.march.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity anapaula.pessanha.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity aureliodutra.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity braulio.goncalves@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity carolina.bittencourt@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity crisbarroso.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity cristiano.mussoi@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity diegomaravilha.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity elenuza@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity erlener.sales.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity evandro.luciano.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity fabiana.nascimento.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity ffqueiroz.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity fabricio.viana.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity gilvana_gomes.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity glaucia.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity helbia@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity jorge.l.mello.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity julibarros.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity julio.r.alves.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity karen.lhayany.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity liviaoliveira.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity luciane.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity luiz.felix.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity felipe.bernardes@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity maira.dubiela.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity marcelo.s.santana.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity marcio.jose@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity marbarbosa@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity marilia.faustino.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity araujo.tecab@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity odimaraquintanilha.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity pamilla.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity paulobacelar.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity rakelli.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity raphael.fassy.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity ricardo.fidelis.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity rogerio_brandao.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity ronaldo.a.alves.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity sergio.s.dutra.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity shayanemarinho.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity simoneferreira.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity suelem.carvalho.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity taissaandressa.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity tania.elis@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity thiago_pereira.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity tfpetronilho.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity vinicius.s.lima.prestserv@petrobras.com.br -PolicyName DP-22-CBS-N
Grant-CsTenantDialPlan -Identity lso.leo@petrobras.com.br -PolicyName DP-BR-22-N
Grant-CsTenantDialPlan -Identity jucinara.prestserv@petrobras.com.br -PolicyName DP-71-TQE-N
Grant-CsTenantDialPlan -Identity luis.almeida@petrobras.com.br -PolicyName DP-BR-27-N
Grant-CsTenantDialPlan -Identity cristiano.n.silva.prestserv@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity joselitocv@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity mvfd@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity taynamartins.prestserv@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity volney.soares@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity csrodrigues@petrobras.com.br -PolicyName DP-21-MNA-N
Grant-CsTenantDialPlan -Identity leandro.correa.prestserv@petrobras.com.br -PolicyName DP-21-MNA-N
Grant-CsTenantDialPlan -Identity rute.costa@petrobras.com.br -PolicyName DP-84-NTL-N
Grant-CsTenantDialPlan -Identity mararubia.INFOTEC@petrobras.com.br -PolicyName DP-BR-13-N
Grant-CsTenantDialPlan -Identity fernanda.trinta.prestserv@petrobras.com.br -PolicyName DP-21-SNDO-N
Grant-CsTenantDialPlan -Identity ingrid.braga.prestserv@petrobras.com.br -PolicyName DP-21-SNDO-N
Grant-CsTenantDialPlan -Identity leonardo.fsouza.prestserv@petrobras.com.br -PolicyName DP-BR-22-N
Grant-CsTenantDialPlan -Identity rafael_lemos@petrobras.com.br -PolicyName DP-21-IFO-N
Grant-CsTenantDialPlan -Identity allancoelho@petrobras.com.br -PolicyName DP-31-BET-N
Grant-CsTenantDialPlan -Identity wasleymadureira.prestserv@petrobras.com.br -PolicyName DP-31-BET-N
Grant-CsTenantDialPlan -Identity sandrodesouza@petrobras.com.br -PolicyName DP-13-EZR-N
